import { readFile, writeFile } from 'node:fs/promises';
import type { Report, ReportFrame } from './regression.js';

export interface DocGeneratorOptions {
  /** Path to the JSON report file. */
  reportPath: string;
  /** Output path for the generated markdown file. */
  outputPath: string;
  /** Project name for the document title. */
  projectName: string;
  /** Scenario name for the subtitle. */
  scenarioName: string;
  /** Scenario description for the intro paragraph. */
  scenarioDescription?: string;
  /** Include frame screenshots as image references. */
  includeScreenshots?: boolean;
  /** Directory path for screenshot references (relative to outputPath). */
  framesDir?: string;
}

/**
 * Generate a markdown documentation file from a recording report.
 * Groups frames by feature, includes descriptions and bug reports,
 * and optionally references screenshot images.
 */
export async function generateDocs(options: DocGeneratorOptions): Promise<string> {
  const {
    reportPath,
    outputPath,
    projectName,
    scenarioName,
    scenarioDescription,
    includeScreenshots = false,
    framesDir,
  } = options;

  let report: Report;
  try {
    const content = await readFile(reportPath, 'utf-8');
    report = JSON.parse(content) as Report;
  } catch {
    throw new Error(`Failed to read report: ${reportPath}`);
  }

  const md = buildMarkdown({
    projectName,
    scenarioName,
    scenarioDescription,
    report,
    includeScreenshots,
    framesDir,
  });

  await writeFile(outputPath, md, 'utf-8');
  return outputPath;
}

interface MarkdownOptions {
  projectName: string;
  scenarioName: string;
  scenarioDescription?: string;
  report: Report;
  includeScreenshots: boolean;
  framesDir?: string;
}

function buildMarkdown(opts: MarkdownOptions): string {
  const { projectName, scenarioName, scenarioDescription, report, includeScreenshots, framesDir } = opts;
  const sections: string[] = [];

  // Title
  sections.push(`# ${projectName} — ${scenarioName}\n`);

  // Description
  if (scenarioDescription) {
    sections.push(`${scenarioDescription}\n`);
  }

  // Metadata
  sections.push(`> Generated from recording on ${report.timestamp}`);
  sections.push(`> Duration: ${formatDuration(report.duration_seconds)} | Frames analyzed: ${report.total_frames_analyzed} | Status: ${report.overall_status}\n`);

  // Summary
  if (report.summary) {
    sections.push(`## Summary\n`);
    sections.push(`${report.summary}\n`);
  }

  // Features demonstrated
  const features = groupByFeature(report.frames);
  if (features.size > 0) {
    sections.push(`## Features Demonstrated\n`);

    for (const [feature, frames] of features) {
      sections.push(`### ${feature}\n`);

      for (const frame of frames) {
        const timestamp = frame.timestamp;
        const statusBadge = getStatusBadge(frame.status);
        sections.push(`- **[${timestamp}]** ${statusBadge} ${frame.description}`);

        if (includeScreenshots && framesDir) {
          const frameFile = `frame-${String(frame.index).padStart(3, '0')}.png`;
          sections.push(`  ![Frame ${frame.index}](${framesDir}/${frameFile})`);
        }
      }

      sections.push('');
    }
  }

  // Bug report
  const bugsFrames = report.frames.filter((f) => f.bugs_detected.length > 0);
  if (bugsFrames.length > 0) {
    sections.push(`## Bugs Detected\n`);
    sections.push(`Found **${report.bugs_found}** bug(s):\n`);

    for (const frame of bugsFrames) {
      for (const bug of frame.bugs_detected) {
        sections.push(`- **[${frame.timestamp}]** ${bug}`);
      }
    }

    sections.push('');
  }

  // Timeline
  if (report.frames.length > 0) {
    sections.push(`## Timeline\n`);
    sections.push(`| Time | Status | Description |`);
    sections.push(`|------|--------|-------------|`);

    for (const frame of report.frames) {
      const status = getStatusBadge(frame.status);
      const desc = frame.annotation_text || frame.description;
      sections.push(`| ${frame.timestamp} | ${status} | ${desc} |`);
    }

    sections.push('');
  }

  // Footer
  sections.push(`---\n`);
  sections.push(`*Generated by [auto-demo-recorder](https://github.com/MashellHan/auto-demo-recorder)*`);

  return sections.join('\n');
}

function groupByFeature(frames: ReportFrame[]): Map<string, ReportFrame[]> {
  const groups = new Map<string, ReportFrame[]>();

  for (const frame of frames) {
    const feature = frame.feature_being_demonstrated || 'General';
    const existing = groups.get(feature) ?? [];
    existing.push(frame);
    groups.set(feature, existing);
  }

  return groups;
}

function getStatusBadge(status: string): string {
  switch (status) {
    case 'ok':
      return '✅';
    case 'warning':
      return '⚠️';
    case 'error':
      return '❌';
    default:
      return '❓';
  }
}

function formatDuration(seconds: number): string {
  const mins = Math.floor(seconds / 60);
  const secs = Math.floor(seconds % 60);
  if (mins > 0) {
    return `${mins}m ${secs}s`;
  }
  return `${secs}s`;
}
